name: HawkScan
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
